// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdhmaimqcjtfbcxhibhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkaG1haW1xY2p0ZmJjeGhpYmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzE1NTUsImV4cCI6MjA2NzQ0NzU1NX0.WjZbhWFSltomPLMqTlW4Of2wgFwS_P4Z3edgEeGC4og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});